- name: Install fonts
  tags:
    - fonts
  vars:
    - fonts:
      - name: FiraCode
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip
      - name: Symbols
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/NerdFontsSymbolsOnly.zip

  block:
    - name: Ensure fonts folder exist
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        mode: '0755'

    - name: Download font
      with_items: "{{ fonts }}"
      ansible.builtin.unarchive:
        src: "{{ item.url }}"
        dest: ~/.fonts
        remote_src: yes

    - name: Install downloaded fonts
      ansible.builtin.shell: >
        fc-cache -fv
